#!/bin/bash
# =============================================================================
# Local Supabase Lifecycle
# =============================================================================
# Wraps the Supabase CLI for the FlowGraph project.
#
# Usage:
#   ./scripts/db.sh start     # start the local stack (Docker)
#   ./scripts/db.sh stop      # stop the local stack
#   ./scripts/db.sh status    # print URLs and keys
#   ./scripts/db.sh reset     # wipe + re-apply migrations
#   ./scripts/db.sh migrate   # apply pending migrations without wiping data
#   ./scripts/db.sh sync-env  # write VITE_SUPABASE_* values into .env.local
# =============================================================================

set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT="$( cd "$SCRIPT_DIR/.." && pwd )"

require_cli() {
  if ! command -v supabase >/dev/null 2>&1; then
    echo "ERROR: supabase CLI not found. Install with: brew install supabase/tap/supabase" >&2
    exit 1
  fi
  if ! command -v docker >/dev/null 2>&1; then
    echo "ERROR: docker not found. Install Docker Desktop: https://www.docker.com/products/docker-desktop" >&2
    exit 1
  fi
  if ! docker info >/dev/null 2>&1; then
    echo "ERROR: Docker daemon is not running. Start Docker Desktop and retry." >&2
    exit 1
  fi
}

cmd_start() {
  require_cli
  cd "$PROJECT_ROOT"
  supabase start
  cmd_sync_env
}

cmd_stop() {
  require_cli
  cd "$PROJECT_ROOT"
  supabase stop
}

cmd_status() {
  require_cli
  cd "$PROJECT_ROOT"
  supabase status
}

cmd_reset() {
  require_cli
  cd "$PROJECT_ROOT"
  supabase db reset
}

cmd_migrate() {
  require_cli
  cd "$PROJECT_ROOT"
  # `supabase migration up` only applies pending migrations against the
  # already-running local DB without wiping it.
  supabase migration up
}

# Pull the local API URL + anon key out of `supabase status` and write
# them to .env.local so Vite can pick them up.
cmd_sync_env() {
  cd "$PROJECT_ROOT"
  local status_output
  if ! status_output="$(supabase status 2>/dev/null)"; then
    echo "WARN: supabase not running; cannot sync .env.local" >&2
    return 0
  fi

  local api_url anon_key
  api_url="$(printf '%s\n' "$status_output" | awk -F': +' '/API URL/ {print $2; exit}')"
  anon_key="$(printf '%s\n' "$status_output" | awk -F': +' '/anon key/ {print $2; exit}')"

  if [ -z "$api_url" ] || [ -z "$anon_key" ]; then
    echo "WARN: could not parse API URL / anon key from supabase status" >&2
    return 0
  fi

  cat > "$PROJECT_ROOT/.env.local" <<EOF
# Auto-generated by ./scripts/db.sh. Do not edit by hand.
VITE_SUPABASE_URL=$api_url
VITE_SUPABASE_ANON_KEY=$anon_key
EOF
  echo "Wrote $PROJECT_ROOT/.env.local"
}

case "${1:-}" in
  start)    cmd_start ;;
  stop)     cmd_stop ;;
  status)   cmd_status ;;
  reset)    cmd_reset ;;
  migrate)  cmd_migrate ;;
  sync-env) cmd_sync_env ;;
  *)
    echo "Usage: $0 {start|stop|status|reset|migrate|sync-env}" >&2
    exit 1
    ;;
esac
